name: Go Workflow

on:
  push:
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.6'
      
      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
  
      - name: Run staticcheck
        run: staticcheck ./...
  
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
  
      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -v ./...
      
      - name: Generate test report
        uses: robherley/go-test-action@v0.1.0

# https://sparkbox.com/foundry/go_vet_gofmt_golint_to_code_check_in_Go
# https://staticcheck.dev/